### ISSUE TITLE
Add KnpLabsFriendlyContexts Alice

### ISSUE THREAD

**Issue by alexisLefebvre** [alexislefebvre/AsyncTweetsBundle#26]

**Comment by alexisLefebvre** [comment]
See:
- https://github.com/KnpLabs/FriendlyContexts/blob/master/doc/context-alice.md
- https://github.com/nelmio/alice

**Comment by alexislefebvre** [comment]
Dependencies were broken because of this:

>

**Comment by alexisLefebvre** [comment]
Dependencies were broken because of this:

> Files will be loaded following the order of files declaration in your behat.yml file. Tags order has no impact.

**Comment by alexisLefebvre** [comment]
See #24 and #22.
